#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""配置和常量（从 speed_test.py 导入，保持单一数据源）"""

# 所有常量从 speed_test.py 导入，避免重复定义
# 直接访问相关常量请 import speed_test 或 from .speed_test import XXX

from .speed_test import (
    VERSION, MIHOMO_REPO,
    MIHOMO_DIR, OUTPUT_DIR, SUBSCRIBE_FILE,
    TCP_PING_CONCURRENCY, TCP_PROBE_CONCURRENCY, TCP_PROBE_TIMEOUT,
    HTTP_LATENCY_TIMEOUT, HTTP_DOWNLOAD_TIMEOUT,
    STREAMING_TEST_TIMEOUT, IP_QUALITY_TIMEOUT,
    SPEED_TEST_URLS, SPEED_COLORS, MIN_SPEED_BYTES,
    DOWNLOAD_CONNS, SLOW_ABORT_SECONDS, SLOW_ABORT_BYTES,
    UDP_TYPES, DEFAULT_WORKERS, MAX_WORKERS,
    SPEED_WINDOW_DEFAULT_SECONDS, SPEED_WINDOW_FAST_SECONDS,
    IP_CHECK_INTERVAL, IP_SOURCES,
    COMMON_STREAMING_SERVICES,
    WPS_INTERNATIONAL_URLS, WPS_CN_URLS,
)
